# Generated by Django 4.1 on 2024-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_kvs',
            name='insurance_status',
            field=models.CharField(blank=True, choices=[('Insured', 'Insured'), ('Not Insured', 'Not Insured')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='paid_month',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='renewal',
            field=models.CharField(blank=True, choices=[('Renewed', 'Renewed'), ('Not Renewed', 'Not Renewed')], max_length=25, null=True),
        ),
    ]
