# Generated by Django 5.1 on 2024-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0002_join_kvs_insurance_status_join_kvs_paid_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_kvs',
            name='union',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
