# Generated by Django 5.1 on 2024-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0003_alter_join_kvs_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_kvs',
            name='data_enter_by_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='data_enter_by_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
