# Generated by Django 4.2.7 on 2024-09-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0006_alter_sakha_taluk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databank",
            name="district",
            field=models.CharField(
                choices=[
                    ("Trivandrum", "Trivandrum"),
                    ("Kollam", "Kollam"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kottayam", "Kottayam"),
                    ("Idukki", "Idukki"),
                    ("Ernakulam", "Ernakulam"),
                    ("Thrissur", "Thrissur"),
                    ("Palakkad", "Palakkad"),
                    ("Malappuram", "Malappuram"),
                    ("Kozhikode", "Kozhikode"),
                    ("Wayanad", "Wayanad"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                ],
                max_length=250,
            ),
        ),
    ]
