# Generated by Django 4.2.7 on 2024-09-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0007_alter_databank_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databank",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
