# Generated by Django 4.2.7 on 2024-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0008_alter_databank_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="join_kvs",
            name="occupation",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="join_kvs",
            name="place",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
