# Generated by Django 4.2.7 on 2024-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0009_join_kvs_occupation_alter_join_kvs_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="join_kvs",
            name="family_members",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
