# Generated by Django 4.2.7 on 2024-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0010_join_kvs_family_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databank",
            name="contact_person",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
