# Generated by Django 4.2.7 on 2024-10-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0011_alter_databank_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="join_kvs",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
