# Generated by Django 4.2.7 on 2024-11-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kvs_app", "0012_join_kvs_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="join_kvs",
            name="id_proof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kvs_app.id_details_choices",
            ),
        ),
    ]
