# Generated by Django 5.1.3 on 2024-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0013_alter_join_kvs_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecommitie',
            name='position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('vice_president', 'Vice President'), ('joint_secretary', 'Joint Secretary'), ('working_committee', 'Working Committee')], default='working_committee', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='databank',
            name='status',
            field=models.CharField(choices=[('Hide', 'Hide'), ('Unhide', 'Unhide')], default='Hide', max_length=25),
        ),
    ]
