# Generated by Django 5.1.3 on 2024-12-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0015_alter_statecommitie_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sakha',
            name='taluk_union',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='kvs_app.taluk'),
        ),
        migrations.AlterField(
            model_name='sakha',
            name='taluk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
