# Generated by Django 5.1.3 on 2024-12-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0018_taluukmember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaluukMember',
            new_name='TalukMember',
        ),
    ]
