# Generated by Django 5.1.3 on 2024-12-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0019_rename_taluukmember_talukmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taluk',
            name='taluk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
