# Generated by Django 5.1.3 on 2024-12-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0023_alter_statecommitie_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sakhamember',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talukmember',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
